### ISSUE TITLE
[SUGGESTION] Add movement offset for HUD.

### ISSUE THREAD

**Issue by roboboredom** [A5b84/status-effect-bars#9]
It would be nice if I could lower the max height (on the screen) of the HUD status effects, as currently with 1+ effect icons displayed, when using mods such as sodium extras that display the coordinates and FPS in the top right the first, topmost effect is obscured.

Example with Dolphin's Grace effect (see top right of image).
![image](https://user-images.githubusercontent.com/57413665/230248952-c2b10184-0a22-4dbe-8df1-d903cafbeb5e.png)

**Comment by A5b84** [comment]
If that's caused by Sodium Extra then I feel like Sodium Extra should be the one fixing this (my mod just renders its bars wherever the status effects are, so if the effects are moved properly the bars will also move)

In the meantime I guess you can use the 'Orthogonal Offset' setting to move the bar a bit lower

**Comment by roboboredom** [comment]
Will do.
